# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

os: Visual Studio 2019

platform:
  - x64

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019 Win64" ..
  - cmake --build . --config Release